### ISSUE TITLE
Make text copyable!

### ISSUE THREAD

**Issue by svmorris** [Authentura/codectrl#20]
The text in the interface cannot be highlighted, or copied in any way. Would it be possible to change that?
Being able to copy is really useful for writing notes, reports etc and would be good if I didn't have to type out the contents of the message.

If it is a limitation of the GUI framework, then maybe we could add some standard method that works everywhere, eg: double-click text to copy it or something like that.

**Comment by STBoyden** [comment]
This is unfortunately a limitation of the GUI framework, and additionally it would require *a lot* of changes and it would mean a lot of branching in the code due to the way how egui checks for interactions. As far as I am aware, it's rare for GUI frameworks to allow for highlighting and copying of any text on an interface. *What I can do* is make it so important pieces of text can be easily copyable, for example: the message, the time or the host in the details view.

**Comment by STBoyden** [comment]
I can address this soon.

**Comment by svmorris** [comment]
Yea I thought that might be an issue. That does beg the question of how its done in most other programs? Like do they just implement their own text highlighting?

Regardless what you said you would do, while obviously not perfect, its good enough. Thank you :slightly_smiling_face: !

**Comment by STBoyden** [comment]
Implemented since 508b54cfab5009012c5af6b28476a14d0fcbba4c.
